config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'videos#index'

  resources :videos do
    resources :reactions, only: :destroy do
      collection do
        post :like
        post :dislike
      end
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def klass
    self.class.table_name.singularize
  end

  def query_selector
    "record_#{klass}_#{id}".camelize
  end
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :current_user
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  belongs_to :notificationable, polymorphic: true
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notifications, dependent: :destroy
end

app/models/video.rb
# frozen_string_literal: true

class Video < ApplicationRecord
  attr_accessor :youtube_url

  belongs_to :creator, class_name: 'User'
  has_many :reactions, class_name: 'VideoReaction', dependent: :destroy
  has_many :notifications, as: :notificationable, dependent: :destroy

  validates :title, presence: true
  validates :youtube_video_id, presence: { message: "can't be blank or wrong video link" },
                               uniqueness: { scope: :creator_id, message: 'cannot share twice' }

  after_create_commit :send_notification

  def create_reaction(kind:, user:)
    reaction = reactions.where(user: user).first_or_initialize
    reaction.update(kind: kind)
  end

  private

  def message
    I18n.t('video_notification_messages', user_email: creator.email,
                                          title: title,
                                          video_id: id)
  end

  def send_notification
    User.where.not(id: creator.id).find_each do |user|
      Notification.create(message: message, user: user, notificationable: self)
      push_notification(user: user)
      update_notification_list(user: user)
    end
  end

  def push_notification(user:)
    broadcast_append_to(user, :videos, target: 'notifications',
                                       partial: 'notifications/new',
                                       locals: { message: { notice: message }, user: user })
  end

  def update_notification_list(user:)
    broadcast_update_to(user, :reactions, target: 'notify-list',
                                          partial: 'notifications/list',
                                          locals: { user: user })
  end
end

app/models/video_reaction.rb
# frozen_string_literal: true

class VideoReaction < ApplicationRecord
  TYPES = %w[like dislike].freeze

  belongs_to :user
  belongs_to :video

  has_many :notifications, as: :notificationable, dependent: :destroy

  validates :kind, inclusion: { in: TYPES }

  scope :likes, -> { where(kind: :like) }
  scope :dislikes, -> { where(kind: :dislike) }

  after_commit :send_notification
  after_commit :update_reaction

  def self.liked?(user:)
    likes.exists?(user: user)
  end

  def self.disliked?(user:)
    dislikes.exists?(user: user)
  end

  private

  def send_notification
    return unless persisted?
    return if Current.current_user == video.creator

    Notification.create(message: message, user: video.creator, notificationable: self)

    push_notification
    update_notification_list
  end

  def message
    I18n.t('reaction_notification_messages', user_email: user.email,
                                             title: video.title,
                                             video_id: video.id,
                                             reaction_kind: kind.humanize.downcase)
  end

  def push_notification
    broadcast_append_to(video.creator, :reactions, target: 'notifications',
                                                   partial: 'notifications/new',
                                                   locals: { message: { notice: message } })
  end

  def update_notification_list
    broadcast_update_to(video.creator, :reactions, target: 'notify-list',
                                                   partial: 'notifications/list',
                                                   locals: { user: video.creator })
  end

  def update_reaction
    broadcast_update_to :update_reaction, target: "video-like-reaction-#{video.id}", html: video.reactions.likes.size

    broadcast_update_to :update_reaction, target: "video-dislike-reaction-#{video.id}", html: video.reactions.dislikes.size
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :assign_current_user

  private

  def assign_current_user
    Current.current_user = current_user
  end

  def not_found
    render :file => Rails.root.join('public/404.html'), layout: false, status: :not_found
  end

  rescue_from ActiveRecord::RecordNotFound, with: :not_found
end

app/controllers/reactions_controller.rb
# frozen_string_literal: true

class ReactionsController < ApplicationController
  def like
    video.create_reaction(kind: :like, user: current_user)
  end

  def dislike
    video.create_reaction(kind: :dislike, user: current_user)
  end

  def destroy
    video.reactions.find_by(user: current_user).destroy
  end

  private

  def video
    @video ||= Video.find_by(id: params[:video_id])
  end
end

app/controllers/videos_controller.rb
# frozen_string_literal: true

class VideosController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    load_videos
  end

  def new; end

  def show
    @video = Video.find(params[:id])
  end

  def create
    service = Youtube::VideoCreator.new(youtube_url: youtube_url, user: current_user)

    if service.perform
      load_videos

      flash.now[:notice] = 'Share Youtube video successfully'
      render :create, status: :ok
    else
      flash.now[:error] = service.error_sentence
      render :create, status: :bad_request
    end
  end

  private

  def load_videos
    @videos = Video.order(created_at: :desc)
  end

  def youtube_url
    params.require(:video).fetch(:youtube_url, '')
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/reactions_helper.rb
# frozen_string_literal: true

module ReactionsHelper
end

app/views/layouts/_head.html.erb
<title>Youtube Sharing Video</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Lato:300,400,700" %>
<%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

app/views/layouts/_user_actions.html.erb
<% if user_signed_in? %>
  <div class="form-control">
    <button class="btn btn-primary" data-controller="turbo-fetch" data-url="<%= new_video_path %>">Share Video</button>
  </div>

  <div id="notify-list" class="form-control">
    <%= render NotificationListComponent.new %>
  </div>

  <div class="dropdown dropdown-end">
    <label tabindex="0" class="btn btn-ghost btn-circle avatar">
      <div class="w-10 rounded-full">
        <img src="https://t4.ftcdn.net/jpg/04/08/24/43/360_F_408244382_Ex6k7k8XYzTbiXLNJgIL8gssebpLLBZQ.jpg" />
      </div>
    </label>
    <ul tabindex="0" class="mt-3 p-2 drop-shadow-2xl menu menu-compact dropdown-content bg-base-100 rounded-box w-52">
      <li>
        <a href="#"><%= current_user.email %></a>
      </li>
      <li>
        <%= link_to 'Logout', destroy_user_session_path, data: { turbo_method: :delete } %>
      </li>
    </ul>
  </div>

<% else %>
  <div class="flex justify-center items-center gap-4">
    <%= form_for User.new, url: user_session_path, method: :post do |f| %>
      <div class="flex justify-center items-center gap-4">
        <%= f.email_field :email, class: 'input w-full max-w-xs border', placeholder: 'Email' %>
        <%= f.password_field :password, class: 'input w-full max-w-xs border', placeholder: 'Password' %>
        <%= f.submit 'Login', class: 'btn btn-primary' %>
      </div>
    <% end %>
    <%= link_to 'Register', new_user_registration_path, class: 'btn' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>

  <body>
    <%= turbo_stream_from current_user, :videos %>
    <%= turbo_stream_from current_user, :reactions %>
    <%= turbo_stream_from :update_reaction %>

    <div id="notifications" class="toast toast-end z-[1000]">
      <%= render ToastrComponent.new(flash: flash) %>
    </div>

    <main class="container mx-auto">
      <div class="navbar bg-base-100">
        <div class="flex-1">
          <%= link_to root_path, class: 'font-semibold cursor-pointer normal-case text-xl ml-5' do %>
            Youtube Sharing Video
          <% end %>
        </div>
        <div class="flex-none gap-2">
          <%= render 'layouts/user_actions' %>
        </div>
      </div>
      <%= yield %>
      <div id="modal" class="modal"></div>
    </main>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html data-theme="garden">
  <head>
    <%= render 'layouts/head' %>
  </head>

  <body class="antialiased">
    <main class="flex min-h-screen items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
      <div class="w-full max-w-md space-y-8">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/notifications/_list.html.erb
<%= render NotificationListComponent.new(user: user) %>

app/views/notifications/_new.html.erb
<%= render ToastrComponent.new(flash: message) %>

app/views/reactions/_update.turbo_stream.erb
<%= turbo_stream.update "#{@video.query_selector}_like" do %>
  <%= render LikeComponent.new(video: @video) %>
<% end %>

<%= turbo_stream.update "#{@video.query_selector}_dislike" do %>
  <%= render DislikeComponent.new(video: @video) %>
<% end %>

app/views/reactions/destroy.turbo_stream.erb
<%= render 'update' %>

app/views/reactions/dislike.turbo_stream.erb
<%= render 'update' %>

app/views/reactions/like.turbo_stream.erb
<%= render 'update' %>

app/views/videos/create.turbo_stream.erb
<%= turbo_stream.update(:notifications) { render(ToastrComponent.new(flash: flash)) } %>
<%= turbo_stream.update 'modal', nil %>

<% if @videos.present? %>
  <%= turbo_stream.update 'video_list' do %>
    <%= render VideoComponent.with_collection(@videos) %>
  <% end %>
<% end %>

app/views/videos/index.html.erb
<div class="w-full h-content">
  <div class="mx-auto max-w-2xl py-16 px-8 sm:py-24 sm:px-6 lg:max-w-full">

    <div id="video_list" class="grid grid-cols-1 gap-y-4 sm:grid-cols-2 sm:gap-x-6 sm:gap-y-10 lg:grid-cols-3 lg:gap-x-8 xl:grid-cols-4 xl:gap-x-8">
      <%= render VideoComponent.with_collection(@videos) %>
    </div>
  </div>
</div>

app/views/videos/new.html.erb
<h3 class="text-lg font-bold my-4">Share a Youtube Video</h3>

<%= simple_form_for Video.new, url: videos_path, method: :post do |f| %>
  <div class="space-y-3">
    <%= f.input :youtube_url, input_html: { class: 'input w-full border border-zinc-300' }, placeholder: 'Youtube Link', label: false, wrapper_html: { class: 'px-0' } %>
    <%= f.error :youtube_video_id, id: 'youtube_video_id' %>
    <%= f.submit 'Share', class: 'btn btn-primary w-full', data: { disable_with: true } %>
  </div>
<% end %>

app/views/videos/new.turbo_stream.erb
<%= turbo_stream.update 'modal' do %>
  <div class="modal-box relative" data-controller="modal">
    <label for="my-modal-3" class="btn btn-sm btn-circle absolute right-2 top-2 modal-close">✕</label>
    <h3 class="text-lg font-bold mb-4">Share a Youtube Video</h3>

    <%= simple_form_for Video.new, url: videos_path, method: :post, remote: true do |f| %>
      <div class="space-y-3">
        <%= f.input :youtube_url, input_html: { class: 'input w-full border border-zinc-300', type: :text }, placeholder: 'Youtube Link', label: false, wrapper_html: { class: 'px-0' } %>
        <%= f.error :youtube_video_id, id: 'youtube_video_id' %>
        <%= f.submit 'Share', class: 'btn btn-primary w-full', data: { disable_with: true } %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/videos/show.html.erb
<div class="px-5 my-5">
  <div id="video_<%= @video.id %>" class="group relative flex flex-col overflow-hidden rounded-lg border border-gray-200 bg-white shadow-lg">
    <div class="aspect-w-4 aspect-h-2 bg-gray-200 group-hover:opacity-75 sm:aspect-none sm:h-46">
      <%= link_to "https://youtu.be/#{@video.youtube_video_id}", target: '_blank' do %>
        <img src="<%= @video.thumbnails.with_indifferent_access[:high][:url] %>" alt="" class="h-full w-full object-cover object-center sm:h-full sm:w-full">
      <% end %>
    </div>
    <div class="flex flex-1 flex-col space-y-2 p-4">
      <h2 class="text-base font-bold text-gray-900">
        <%= @video.channel_name %>
      </h2>
      <%= link_to "https://youtu.be/#{@video.youtube_video_id}", target: '_blank' do %>
        <h3 class="text-sm font-medium text-gray-900">
          <%= @video.title %>
        </h3>
      <% end %>
      <h3>Shared by: <%= @video.creator.email %></h3>

      <div class="feedback flex items-center gap-3">
        <div id='<%= "#{@video.query_selector}_like" %>'>
          <%= render LikeComponent.new(video: @video) %>
        </div>

        <div id='<%= "#{@video.query_selector}_dislike" %>'>
          <%= render DislikeComponent.new(video: @video) %>
        </div>
      </div>

      <p class="text-sm text-gray-800"><%= @video.description.to_s[0..200] %>...</p>
    </div>
  </div>
</div>